// Centralized glossary — single source of truth for all hoverable jargon.
// To add an alias, just add another key with the same definition string.
// Plurals need explicit entries (the regex uses \b word boundaries).
export const glossary = {
  // ── Foundational ML ────────────────────────────────────────
  "Perceptron": "The first trainable neural model (1958) — a single layer of weights that can classify linearly separable patterns.",
  "Backpropagation": "Algorithm that computes gradients of the loss w.r.t. every weight by applying the chain rule layer by layer.",
  "Backprop": "Backpropagation — computing gradients of the loss w.r.t. every weight by applying the chain rule layer by layer.",
  "Chain rule": "Calculus rule for derivatives of composed functions: d(f(g(x)))/dx = f'(g(x))·g'(x). The mathematical foundation of backprop.",
  "Gradient": "The derivative of the loss function with respect to a weight; indicates the direction and magnitude to adjust it.",
  "Gradients": "Derivatives of the loss function with respect to weights; indicate the direction and magnitude to adjust them.",
  "Gradient descent": "Optimization algorithm that iteratively adjusts weights in the direction that reduces the loss function.",
  "Loss function": "A mathematical function measuring how wrong the model's predictions are; training minimizes this.",
  "Hidden layer": "A neural network layer between input and output whose learned representations are not directly observed.",
  "Hidden layers": "Neural network layers between input and output whose learned representations are not directly observed.",
  "Hidden state": "An internal vector updated at each timestep, serving as the network's working memory of past inputs.",
  "Hidden states": "Internal vectors at each position in a sequence, carrying the network's learned representations.",
  "Feedforward": "A neural network architecture where data flows in one direction (input to output) with no recurrent connections.",
  "Activation function": "A non-linear function (ReLU, sigmoid, etc.) applied after each layer, enabling the network to learn non-linear patterns.",
  "Sigmoid": "S-shaped activation function squashing values to (0, 1), used in LSTM gates and binary classification.",
  "Linearly separable": "Data that can be perfectly divided by a hyperplane — the fundamental limit of single-layer networks like the perceptron.",
  "XOR": "Exclusive OR — a classic logic function that is not linearly separable, proving perceptrons have fundamental limits.",
  "End-to-end training": "Training the entire model jointly from raw input to final output, rather than optimizing components separately.",
  "AI winter": "Periods (1970s, late 1980s–90s) of reduced funding and interest in AI, triggered by unmet hype and theoretical critiques.",
  "Recurrence": "Feeding a network's output back as input at the next timestep, creating a loop that carries state across time.",
  "Vanishing gradient": "Gradients shrink toward zero as they pass through many layers or timesteps, halting learning in deep networks.",
  "Constant error carousel": "The LSTM's cell state pathway that allows gradients to flow unchanged across many timesteps, preventing vanishing gradients.",
  // ── Recurrent Networks ─────────────────────────────────────
  "RNN": "Recurrent Neural Network — processes sequences by maintaining a hidden state that feeds back at each timestep.",
  "RNNs": "Recurrent Neural Networks — process sequences by maintaining a hidden state that feeds back at each timestep.",
  "Recurrent neural network": "A network with feedback loops that processes sequences by maintaining hidden state across timesteps.",
  "Recurrent neural networks": "Networks with feedback loops that process sequences by maintaining hidden state across timesteps.",
  "Recurrent net": "A recurrent neural network — processes sequences by maintaining hidden state across timesteps.",
  "BPTT": "Backpropagation Through Time — unrolling a recurrent net across timesteps and applying the chain rule.",
  "Backpropagation through time": "Unrolling a recurrent net across timesteps and applying the chain rule — the standard way to train RNNs.",
  "LSTM": "Long Short-Term Memory — a gated recurrent network with a cell state that captures long-range dependencies.",
  "LSTMs": "Long Short-Term Memory networks — gated recurrent networks with cell states that capture long-range dependencies.",
  "Gated cell state": "A memory vector controlled by learned sigmoid gates that regulate what information to store, forget, or output.",
  // ── NLP / Sequence Modeling ────────────────────────────────
  "NLP": "Natural Language Processing — the field of AI focused on understanding and generating human language.",
  "Token": "The basic unit of text (word, subword, or character) that a language model processes.",
  "Tokens": "Basic units of text (words, subwords, or characters) that a language model processes.",
  "Corpus": "A large collection of text used for training language models.",
  "Language modeling": "The task of predicting the next token in a sequence — the core training objective for most LLMs.",
  "Language model": "A model trained to predict or generate text, typically by predicting the next token in a sequence.",
  "Language models": "Models trained to predict or generate text, typically by predicting the next token in a sequence.",
  "Next-token prediction": "Training objective where the model learns to predict each successive token given all preceding tokens.",
  "Downstream task": "A specific application (classification, QA, translation) that a pre-trained model is adapted to.",
  "Labeled dataset": "Training data where each example has a human-provided correct answer or annotation.",
  "Labeled datasets": "Training data where each example has a human-provided correct answer or annotation.",
  "Embedding": "A dense vector representation of a discrete input (word, token, image patch) in continuous space.",
  "Embeddings": "Dense vector representations of discrete inputs (words, tokens, patches) in continuous space.",
  "Neural machine translation": "Using neural networks to translate text between languages — the task that motivated attention mechanisms.",
  "Word2Vec": "An early method (2013) for learning word embeddings by predicting context words — a precursor to modern pre-training.",
  "ELMo": "Embeddings from Language Models (2018) — contextual word representations via bidirectional LSTMs, a precursor to BERT.",
  "Unidirectional": "Attending only to past tokens (left context), not future ones — the constraint of autoregressive models like GPT.",
  "Seq2seq": "Sequence-to-sequence — an encoder reads input, a decoder generates output token by token.",
  "Information bottleneck": "Forcing all input information through a fixed-dimensional vector, which loses detail on long inputs.",
  "Weighted sum": "Each element gets a learned relevance score; the output is their score-weighted combination.",
  // ── Attention & Transformer Architecture ───────────────────
  "Attention": "Mechanism by which a model dynamically weights different input positions when producing each output element.",
  "Self-attention": "Each token attends to every other token in the same sequence via queries, keys, and values.",
  "Multi-head": "Running several attention functions in parallel, each learning to focus on different relationship patterns.",
  "Attention matrix": "The N×N matrix of pairwise attention scores between all tokens in a sequence.",
  "Scaled dot-product attention": "Core attention: softmax(QK^T / sqrt(d)) · V, where the scaling factor prevents vanishing gradients in softmax.",
  "Softmax": "Function that converts a vector of raw scores (logits) into a probability distribution summing to 1.",
  "Dot product": "Sum of element-wise products of two vectors; measures similarity between query and key vectors in attention.",
  "Encoder": "Component that reads input and produces a sequence of hidden representations.",
  "Decoder": "Component that generates output tokens one at a time, often attending to encoder representations.",
  "Encoder-decoder": "Architecture pairing an encoder (reads input) with a decoder (generates output), connected via cross-attention.",
  "Transformer encoder": "An encoder-only Transformer with no causal mask, attending bidirectionally — used in BERT.",
  "Transformer decoder": "A decoder-only Transformer with causal masking for autoregressive generation — used in GPT.",
  "Layer normalization": "Normalizing activations across features within each layer to stabilize training and improve convergence.",
  "Positional encoding": "Injected signals that tell the model where each token sits in the sequence.",
  "Positional encodings": "Injected signals that tell the model where each token sits in the sequence.",
  "Residual connection": "Adding the input of a sublayer to its output, creating a shortcut that eases gradient flow.",
  "Residual connections": "Adding the input of a sublayer to its output, creating shortcuts that ease gradient flow.",
  // ── Pre-training & Transfer Learning ───────────────────────
  "Autoregressive": "Generating one token at a time, each conditioned on all previous tokens.",
  "Pre-training": "Training on a large unsupervised corpus before task-specific fine-tuning.",
  "Fine-tuning": "Adapting a pre-trained model to a specific task with a small labeled dataset.",
  "Masked language modeling": "Hiding random tokens and training the model to reconstruct them from surrounding context.",
  "Bidirectional context": "Attending to both left and right context simultaneously, unlike autoregressive (left-only) models.",
  // ── Scaling & Emergent Behavior ────────────────────────────
  "LLM": "Large Language Model — a Transformer with billions of parameters trained on massive text corpora.",
  "LLMs": "Large Language Models — Transformers with billions of parameters trained on massive text corpora.",
  "LM": "Language Model — a model trained to predict or generate sequences of tokens.",
  "LMs": "Language Models — models trained to predict or generate sequences of tokens.",
  "Parameters": "The learned numerical weights in a neural network; more parameters generally means more capacity.",
  "Zero-shot": "Performing a task without any task-specific training examples — relying purely on pre-trained knowledge.",
  "Emergent capabilities": "Abilities that appear at larger model scales but are absent at smaller scales.",
  "Zero-shot transfer": "Performing a task the model was never explicitly trained on, using only knowledge from pre-training.",
  "In-context learning": "The model adapts to a task based on examples in the prompt, without any gradient updates.",
  "Few-shot": "Providing a small number of examples in the prompt to demonstrate a task.",
  "Prompt": "The text input given to the model that conditions its generation.",
  "Scaling hypothesis": "The idea that simply making models larger yields qualitatively better, more general capabilities.",
  "Scaling laws": "Empirical power-law relationships between model size, data, compute, and resulting performance.",
  "Forward pass": "One pass through the network from input to output, producing predictions without updating weights.",
  "Weight updates": "Adjusting model parameters using computed gradients — how the model learns from data.",
  "GPU": "Graphics Processing Unit — massively parallel processor used to accelerate neural network training and inference.",
  "GPU-days": "A unit of compute cost: one GPU running for one day. Training frontier models requires thousands of GPU-days.",
  "FLOPS": "Floating Point Operations Per Second — a measure of computational throughput.",
  "Inference": "Using a trained model to generate predictions or outputs, as opposed to training it.",
  // ── Vision ─────────────────────────────────────────────────
  "CNN": "Convolutional Neural Network — uses learned spatial filters to detect local patterns in images.",
  "CNNs": "Convolutional Neural Networks — use learned spatial filters to detect local patterns in images.",
  "Inductive bias": "Built-in assumptions about data structure baked into the architecture (e.g., CNNs assume spatial locality).",
  "Inductive biases": "Built-in assumptions about data structure baked into the architecture (e.g., CNNs assume spatial locality).",
  "Image patches": "Splitting an image into fixed-size tiles (e.g., 16×16 pixels), each treated as a token for the Transformer.",
  "ViT": "Vision Transformer — applies a standard Transformer to sequences of image patches instead of using convolutions.",
  "CLIP": "Contrastive Language-Image Pre-training (2021) — aligns image and text embeddings in a shared space via contrastive learning.",
  "Cross-modal reasoning": "Reasoning that spans multiple input types (e.g., answering questions about an image using text understanding).",
  "Visual encoder": "A ViT-based model converting pixel data into vector embeddings that a language model can process.",
  "Visual encoders": "ViT-based models converting pixel data into vector embeddings that a language model can process.",
  "Multimodal": "Processing multiple modalities (text, images, audio) within a single model.",
  "Embedding space": "The vector space where text and image representations coexist, enabling cross-modal comparison.",
  // ── Mixture of Experts ─────────────────────────────────────
  "Dense model": "A model where all parameters are activated for every input, as opposed to sparse/MoE models.",
  "Expert": "A sub-network within MoE that specializes in certain tokens or input patterns.",
  "Gating function": "A small network that decides which experts each token is routed to.",
  "Expert collapse": "A failure mode where MoE training causes all tokens to be routed to the same few experts.",
  "Load balancing": "Ensuring tokens are distributed evenly across experts in MoE, often via auxiliary loss terms.",
  "Auxiliary loss": "An extra loss term added during training to prevent pathologies like expert collapse in MoE.",
  "Auxiliary losses": "Extra loss terms added during training to prevent pathologies like expert collapse in MoE.",
  // ── Position Encodings ─────────────────────────────────────
  "Absolute position encoding": "A fixed vector for each position index, added to the token embedding. Doesn't generalize to new lengths.",
  "Relative position": "Encoding distance between tokens rather than their absolute indices — enables length generalization.",
  "Length extrapolation": "Handling sequences longer than those seen during training without degraded performance.",
  "RoPE": "Rotary Position Embeddings — encodes relative position by rotating query/key vectors, enabling length extrapolation.",
  // ── Alignment & RLHF ───────────────────────────────────────
  "RLHF": "Reinforcement Learning from Human Feedback — training a reward model on human preferences, then optimizing the LM against it.",
  "Reinforcement learning": "Training paradigm where a model learns from scalar reward signals rather than labeled examples.",
  "RL": "Reinforcement Learning — learning from reward signals rather than supervised labels.",
  "Reward model": "A model trained to predict which of two outputs a human would prefer.",
  "PPO": "Proximal Policy Optimization — a stable reinforcement learning algorithm that constrains policy update size.",
  "KL penalty": "A regularization term preventing the model from straying too far from the pre-trained distribution.",
  "Alignment": "Making model behavior match human values, intentions, and safety requirements.",
  "Policy": "In RL, the learned strategy mapping inputs to actions; for LLMs, the model's text generation distribution.",
  "Critic": "In RL, a model that estimates the expected value of states or actions to help stabilize policy training.",
  "Base model": "The pre-trained model before any alignment, fine-tuning, or RLHF has been applied.",
  "Human annotation": "Human-generated labels, rankings, or feedback used to train reward models or create labeled datasets.",
  "Process reward model": "A reward model that evaluates intermediate reasoning steps, not just final answers.",
  "Process reward models": "Reward models that evaluate intermediate reasoning steps, not just final answers.",
  "Preference pairs": "Two model outputs for the same prompt, one ranked as preferred by a human evaluator.",
  "Binary cross-entropy": "Standard binary classification loss, applied in DPO to preference ranking over output pairs.",
  "Closed-form": "An exact mathematical solution derived analytically, as opposed to iterative numerical optimization.",
  // ── Chain-of-Thought & Reasoning ───────────────────────────
  "Multi-step reasoning": "Problems requiring a sequence of logical steps to reach the correct answer.",
  "Serial compute": "Using multiple sequential output tokens to work through harder problems step by step.",
  "Reasoning chain": "A sequence of intermediate reasoning steps the model generates before producing a final answer.",
  "Reasoning chains": "Sequences of intermediate reasoning steps a model generates before producing final answers.",
  // ── Efficiency & Systems ───────────────────────────────────
  "HBM": "High Bandwidth Memory — large but relatively slow GPU memory where the attention matrix is typically stored.",
  "SRAM": "Static RAM — small but very fast on-chip memory used for tiled computation in FlashAttention.",
  "Tiling": "Breaking large matrix operations into blocks that fit in fast on-chip SRAM to reduce slow HBM accesses.",
  "Kernel fusion": "Combining multiple GPU operations into a single kernel to reduce memory reads/writes between operations.",
  "FlashAttention": "An IO-aware attention algorithm that uses tiling and kernel fusion to avoid materializing the full N×N attention matrix.",
  "Quadratic attention": "Standard attention's O(N²) cost in time and memory from computing all pairwise token interactions.",
  "Sparse attention": "Attending to only a subset of token pairs rather than all N², reducing cost for long sequences.",
  // ── KV Cache & Inference Efficiency ────────────────────────
  "KV cache": "Stored key/value matrices reused during autoregressive inference to avoid redundant recomputation.",
  "Query/key/value heads": "Parallel attention projections that produce Q, K, V vectors in separate learned subspaces.",
  "GQA": "Grouped-Query Attention — multiple query heads share one key-value head, reducing KV cache size.",
  "Multi-Query Attention": "An extreme form of GQA using a single KV head for all query heads — fast but lower quality than GQA.",
  "Ablations": "Systematic experiments where components are removed or varied to measure their individual contribution.",
  // ── Long Context ───────────────────────────────────────────
  "Context window": "The maximum number of tokens a model can process in a single forward pass.",
  "NTK-aware scaling": "Adjusting RoPE rotation frequencies using Neural Tangent Kernel theory for length extrapolation.",
  "Ring attention": "Distributing the attention computation across GPUs along the sequence dimension for very long inputs.",
  "Sequence parallelism": "Distributing computation along the sequence dimension across multiple GPUs to handle long contexts.",
  "Long context": "The ability to process very long inputs (100K+ tokens), requiring architectural and systems innovations.",
  // ── Test-Time Compute ──────────────────────────────────────
  "Test-time compute": "Additional computation spent during inference (beyond a single forward pass) to improve answer quality.",
  "Self-verification": "The model checking its own intermediate reasoning steps for logical errors or inconsistencies.",
  "Backtracking": "Revising a reasoning path when an error is detected and trying an alternative approach.",
  // ── SSM / Hybrids ──────────────────────────────────────────
  "State-space model": "A sequence model based on discretized linear dynamical systems, offering O(N) complexity.",
  "State-space models": "Sequence models based on discretized linear dynamical systems, offering O(N) complexity.",
  "SSM": "State-Space Model — a linear dynamical system discretized for sequence modeling with O(N) complexity.",
  "Linear attention": "Replacing softmax attention with kernel-based linear recurrences for O(N) instead of O(N²) complexity.",
  "Hybrid": "An architecture interleaving attention layers with SSM or other efficient layers.",
  "Selective gating": "Mamba's key innovation: making SSM parameters input-dependent so the model can selectively remember or forget.",
  // ── Agentic ────────────────────────────────────────────────
  "Function calling": "Structured output (usually JSON) specifying which external tool or API to invoke with what arguments.",
  "Sandboxed execution": "Running code or external tools in an isolated environment to prevent unintended side effects.",
  "Re-planning": "Adjusting the action plan based on observed outcomes from previous tool-use steps.",
  "Instruction following": "A model's ability to accurately understand and execute natural language instructions.",
  "Structured output": "Model output in a defined, parseable format (JSON, XML, function calls) rather than free-form text.",
};
