import 'dotenv/config'
import { prisma } from '../../../lib/prisma'

// Condensed tag descriptions: max knowledge per token for AI classifier
// Focus: what this tag means + how to distinguish from similar tags
const descriptions: Record<number, string> = {
  // === Projects ===
  25: `Parent project for AI 2030 interactive visualization. Use for cross-cutting/shared work spanning multiple sub-features. Use specific sub-tags (Globe, HUD, Graphs, etc.) when work targets one feature.`,
  142: `Documenting changes/release notes for AI 2030. Distinct from feature work (Globe, HUD, etc.) — this is recording WHAT changed, not building changes.`,
  247: `Galaxy/cosmic-themed visualization within AI 2030. Distinct from GalaxyHUD (standalone project) and AI 2030 Globe (geographic visualization). Look for star-field/nebula/galaxy-shaped data clusters.`,
  109: `Globe/map visualization component within AI 2030. Use specific Globe sub-tags for narrow work: Globe Infra (foundational systems), Globe Colorspace (color math), Globe Rect Mode (flat projection), Globe variable hexes (hex grid), Globe Options Bug (settings bug).`,
  110: `Chart/graph data visualizations (line charts, bar charts, etc.) within AI 2030. Distinct from Globe (geographic viz), HUD (overlay UI), Legends (explanatory keys). Distinct from Debug Linechart Data (specifically debugging data issues in line charts).`,
  278: `Heads-up display overlay UI (controls, panels, toggles, info displays) within AI 2030. Distinct from AI 2030 Globe (the visualization itself), AI 2030 Legends (explanatory keys), and GalaxyHUD (separate standalone project).`,
  326: `Legend/key UI components explaining visual encodings within AI 2030. Distinct from Globe Colorspace (color calculations that feed INTO legends) and HUD (interactive controls, not explanatory keys).`,
  342: `Mobile-responsive work for AI 2030. Only applies when work explicitly targets mobile (media queries, touch events, viewport testing). Not just working on AI 2030 features that happen to be visible on mobile.`,
  151: `Contingency/backup plan within AI 2030. Apply ONLY when the literal words "Plan B" appear. Do NOT apply if "plan a" is mentioned instead. Distinct from AI 2030 Strategy (general strategic planning).`,
  325: `Datacenter visualization specifically in rectangular/flat map projection within AI 2030. Distinct from Globe Rect Mode (the rect projection feature generally) and AI 2030 Globe (general globe work).`,
  329: `Political/administrative boundary lines (state/province borders) on the AI 2030 map. Distinct from Globe Infra (foundational rendering), Globe variable hexes (hex grid overlay), and AI 2030 Rect Datacenters (datacenter markers).`,
  264: `High-level strategic planning for AI 2030 — roadmap, priorities, what to build next. Distinct from AI 2030 Plan B (specific contingency triggered by literal "Plan B"), AI Research Meta (general AI research methodology), and the parent AI 2030 tag (hands-on cross-cutting work).`,
  172: `Meta-level work about AI research processes and methodology — how to do AI research, not doing it. Distinct from AI 2030 (a specific visualization project), Talk to AI Futures (conversations about AI trajectories), and AI coding technique tags.`,
  340: `Scheduled external commitments (doctor, dentist, DMV). Distinct from Team Meeting (internal work meetings), Life Admin (general personal admin tasks without a fixed appointment), and Lunch (midday meal).`,
  318: `Contentious discussion/debate specifically about a DC March event. Distinct from DC March (neutral planning/logistics work). If the engagement is argumentative → this tag. If practical/logistical → DC March.`,
  154: `Making predictions concrete and resolvable with clear resolution criteria. Distinct from Fatebook (the platform for tracking predictions) and Bayes Theorem (probability math). This is the upstream work of defining WHAT counts as true/false.`,
  168: `Investigative project about blockquote functionality (likely on LW). The "Hypothesis" suffix = experimental/exploratory. Distinct from LW Writing/Commenting (creating content containing blockquotes) and ExtractionHypothesis (different hypothesis project).`,
  92: `Deliberately taking a break from work (Projects category = time allocation tracking). Distinct from Break (Triggers = the state of being on break) and Take a Break (Techniques = the decision to step away). This logs the TIME spent on break.`,
  133: `Side project related to an organization called CAST. Look for "CAST" in repos/files/Slack. Distinct from Dubious Side Project (a general state of working on questionable side work) — this is a specific named project.`,
  263: `Working ON the Cursor IDE itself — .cursorrules, custom commands, extensions, Cursor configuration. NOT just using Cursor to code (that's every coding session). The "Meta" suffix = building the tool, not using it.`,
  314: `Practical planning/logistics for a DC March event. Distinct from Argue about DC March (contentious debate about the march). Neutral organizational work → DC March. Heated discussion → Argue about DC March.`,
  300: `Debugging DATA issues in line charts specifically — wrong values, missing points, transformation errors. Distinct from AI 2030 Graphs (broader graph work including features) and Debugging CSS (visual styling issues, not data pipeline).`,
  334: `Work on a health-related project for an entity called "EVN". Look for "EVN" in code/URLs/Slack. Distinct from personal health tags (Workout, Appointment) — this is development work on a health product.`,
  259: `Experimental project testing extraction methods/approaches. The "Hypothesis" suffix = investigative. Distinct from AI Extraction Summaries (using AI to extract/summarize — the application, not the investigation of methods).`,
  347: `Time spent on Facebook platform. Platform-specific tracking regardless of purpose. Distinct from Break (general rest), DMing (active messaging), and Dubiously Productive Procrastinating (the avoidance pattern, not the platform).`,
  269: `Building a specific tool for rapid UI testing/verification. Distinct from Rapid Design Infra (technique of building design infrastructure generally) and UI Fiddling (hands-on adjustment, not building test tooling).`,
  249: `Standalone project combining galaxy visuals with HUD interface, OUTSIDE AI 2030. Distinct from AI 2030 Galaxies (galaxy work within AI 2030) and AI 2030 HUD (HUD within AI 2030). Look for "GalaxyHUD" in file paths/repos.`,
  297: `Color math, colorspace conversions, and color mapping for globe visualization. Distinct from Globe Infra (general foundational systems), AI 2030 Legends (legend UI that uses colors), and Globe Rect Mode (projection, not colors).`,
  152: `Foundational infrastructure/architecture for globe rendering — core rendering pipeline, base coordinate systems, shared utilities. Distinct from feature-level Globe tags (Colorspace, Rect Mode, variable hexes). "Am I building the foundation or building on it?"`,
  290: `Specific bug in the options/settings/configuration UI of the globe. Distinct from Globe Infra (foundational systems, not UI options) and other Globe tags. Requires: debugging activity + options/settings UI + an actual defect.`,
  299: `Rectangular/flat 2D map projection mode for the globe. Distinct from Globe Infra (shared systems across all modes), Globe Colorspace (color handling regardless of projection), and AI 2030 Rect Datacenters (datacenter content displayed in rect mode, not the projection feature itself).`,
  173: `Hexagonal grid overlay on globe with variable/adaptive properties (size, density, zoom-dependent). Distinct from Globe Infra (foundational systems hexes build upon), Globe Colorspace (color of hexes, not hex geometry), and Globe Rect Mode (projection mode, different feature).`,
  15: `Parent tag for LessWrong platform work not covered by specific sub-tags. Use sub-tags when applicable: LW Moderation, LW Review, LW Writing, LW Commenting, LW Reading, LW User Request, LW Supermod. This is the default for general/cross-cutting LW work.`,
  102: `Writing comments on LessWrong posts (Projects = time tracking the activity). Distinct from LW Writing (creating full posts/articles), LW Reading (passive consumption), LW Moderation (enforcing standards), and LW Commenting (Techniques = applying specific commenting methodology).`,
  16: `Enforcing community standards on LW — reviewing flagged content, handling reports, moderation decisions. Distinct from LW User Request (service-oriented help for users, not enforcement) and LW Supermod (elevated/meta-moderation).`,
  248: `Passively reading/consuming content on LessWrong. Distinct from LW Commenting (writing comments), LW Writing (creating posts), LW Review (annual review process), and LW Moderation (enforcement work).`,
  63: `Work related to the LessWrong Annual Review process — reviewing/nominating/voting on posts, building review infrastructure. Distinct from LW Reading (general content consumption) and LW Writing (creating new posts). Use sub-tags LW Review Wizard or LW Review Highlight Test for those specific features.`,
  155: `Testing highlight functionality specifically within the LW Review system. Requires all three: LW Review context + highlight feature + testing/QA focus. Distinct from LW Review (general review work) and LW Review Wizard (the guided wizard interface).`,
  320: `Building the step-by-step guided wizard interface for LW's annual review process. Distinct from LW Review (broader review work or participation) and LW Review Highlight Test (testing highlights, different feature).`,
  123: `Elevated/super-moderator functionality on LW — building supermod tools, handling escalated cases, meta-moderation. Distinct from LW Moderation (routine day-to-day moderation). Look for "supermod" in code/URLs.`,
  316: `Handling user-initiated support requests on LW — bug reports, account issues, feature requests. Distinct from LW Moderation (enforcement/violations, not service) — the key difference is service-oriented help vs. enforcement action.`,
  319: `Specific substantial project/mission related to LW user Wei Dai. Look for "Wei Dai" in context. Distinct from LW User Request (general user support) and general LW tags.`,
  153: `Creating original long-form posts/articles for LessWrong publication. Distinct from LW Commenting (shorter responses to existing posts), LW Reading (consuming content), and LW Review (evaluating past posts during annual review).`,
  335: `Personal administrative tasks — bills, insurance, housing, taxes, personal email, scheduling. Distinct from Appointment (attending the scheduled commitment itself), Break (rest/relaxation), and Workout (exercise).`,
  179: `DEVELOPING the logging/time-tracking app (also called "raydom"). Just having LoggerApp open in browser is NOT this tag — requires actively editing source code in Cursor. Distinct from ThoughtLogger (different project for thought capture, not activity tracking).`,
  26: `Eating the midday meal. Being in lunch-related Slack channels is NOT evidence. Distinct from Got Snack (smaller food items), Break (general rest), and Life Admin (personal admin tasks).`,
  17: `Meta-cognitive state of figuring out what to work on, getting bearings, surveying tasks/priorities. Forward-looking. Distinct from Postmortem (backward-looking analysis), Review Yesterday (specifically reviewing prior day), Trump Orienting (specifically processing Trump news), and "What's my Goal?" (a specific in-the-moment question, not a broader orientation phase).`,
  294: `Structured retrospective analysis after an incident/project — root cause analysis, lessons learned, action items. Backward-looking. Distinct from Orienting (forward-looking, figuring out what to do next), Review Yesterday (daily habit, not incident-specific), and Debugging (fixing current issues, not analyzing past ones).`,
  147: `Work on the rationality.training website or its codebase. Apply ONLY when: browsing rationality.training URL or working in Cursor project named "rationality-training". NOT for general rationality-related work on LW.`,
  18: `Personal infrastructure/tooling that supports the user's general workflow — dev environment, dotfiles, personal automation. Distinct from LoggingApp (specific time-tracking app), Cursor Meta (Cursor IDE specifically), ThoughtLogger (specific thought-capture app), Globe Infra (globe-specific), and UI Infra (UI-specific technique).`,
  274: `Organizational/planning work for Solstice events (not venue-specific). Distinct from Solstice Venues (specifically finding/booking venues). "Meta" = event infrastructure/coordination, not direct event execution.`,
  258: `Finding/evaluating/booking venues specifically for a Solstice event. Distinct from Solstice Meta (broader event organization beyond venues) and Wedding Venues (different event type entirely).`,
  346: `Research/writing comparing superintelligence development vs. whole brain emulation/mind uploading as technological paths. Look for "uploading", "WBE", "brain emulation" combined with superintelligence/AGI. Distinct from AI Research Meta (research methodology) and Talk to AI Futures (broader AI trajectory conversations).`,
  313: `Scheduled group meetings with work colleagues (standups, syncs, planning). Distinct from Talk to X tags (1:1 consultations with specific people), Appointment (external/personal commitments), and Talk to Coworker (verbal conversation trigger, not scheduled meeting).`,
  321: `DEVELOPING the ThoughtLogger application (thought/reflection capture tool). Distinct from LoggingApp (activity/time tracking — different app). Only applies when editing ThoughtLogger codebase, NOT when using it to record thoughts.`,
  245: `Processing/understanding Trump-related political news and developments. Distinct from Orienting (general work orientation), DC March (organizing a specific event), and Argue about DC March (debating the march). This is about UNDERSTANDING Trump news, not acting on it.`,
  348: `Time spent on Twitter/X platform. Platform-specific regardless of purpose. Distinct from Facebook and Youtube (different platforms), Break (general rest), and DMing (active private messaging on any platform).`,
  171: `Venue research/booking specifically for a wedding. Distinct from Solstice Venues (different event), Life Admin (general personal admin), and Appointment (attending a venue tour, not the research/coordination itself).`,
  304: `Physical exercise and fitness activities (gym, running, etc.). Distinct from Take a Walk (lighter, mental-reset focused), Break (general rest without exercise), and Appointment (scheduled external commitments).`,
  93: `Time spent on YouTube platform. Platform-specific regardless of purpose (research, entertainment, learning). Distinct from Facebook and Twitter/X (different platforms) and Break (general rest).`,

  // === Techniques ===
  310: `Self-inquiry about fundamental desires/preferences — "what do I genuinely want?" Deeper than "What's my Goal?" (specific objectives) and broader than "What would excite me?" (excitement-specific). About authentic preferences that may differ from stated goals.`,
  311: `Self-inquiry using excitement/enthusiasm as criterion for task selection. Distinct from "What do I want?" (broader desires, not just excitement), "What's my Goal?" (objectives, not emotional engagement), and List low-energy options (matching tasks to LOW energy, not seeking excitement).`,
  260: `Self-inquiry identifying throughput-limiting constraints — "what single factor would unlock the most progress?" Theory of constraints thinking. Distinct from "What's hard about this?" (subjective difficulty) and Identify Constraints (broader listing of all limiting factors, not just the bottleneck).`,
  349: `Self-inquiry optimizing for speed — "which approach is fastest?" Assumes goal is known, asks HOW to reach it quickest. Distinct from "What's my Goal?" (WHAT to accomplish), "What're my bottlenecks?" (diagnostic), and Think It Faster (accelerating cognitive speed itself, not selecting fastest approach).`,
  223: `Self-inquiry clarifying current objective — "what am I actually trying to accomplish?" A pointed in-the-moment question. Distinct from Orienting (broader phase of getting bearings), "What do I want?" (deeper desires/preferences), and "What're my bottlenecks?" (obstacles, not destination).`,
  277: `Deliberately considering 2+ conceptual perspectives/lenses on a design problem (user needs vs. technical constraints vs. aesthetics, etc.). Distinct from 2+ Plans (generating action plans, not design lenses), Agent does design variations (AI generating visual alternatives), and UI Fiddling (hands-on iterative adjustment).`,
  206: `Generating 2+ distinct strategic approaches before choosing one. Distinct from 2+ Design Frames (multiple design perspectives, not action plans), "What's fastest?" (optimizing on one dimension), and Identify Constraints (finding limitations, not generating options).`,
  303: `Asking AI to holistically review code for quality/bugs/improvements. Requires the literal word "review" in the prompt. Distinct from Ask AI to debug (fixing specific bugs) and Ask AI to improve it's code (refining AI's own output). "Review" = comprehensive evaluation.`,
  238: `Using AI to extract/summarize information from documents. Distinct from Ask LLM (noncode) (broader non-code AI use), Distill Takeaways (human-driven synthesis, not AI), and ExtractionHypothesis (investigating extraction methods, not using them).`,
  252: `Asking AI specifically to diagnose root CAUSE of a bug — "what's causing this?" Distinct from Ask AI to debug (delegating full fix), Ask AI to help me do my own debug (human-led with AI support), and Specific Debugging Hypotheses (human generating theories, not AI).`,
  196: `Using AI to diagnose VISUAL/rendering problems (CSS, layout, appearance). Distinct from Debugging CSS (trigger for CSS debugging state, any method), Debug 3D Visuals (trigger for 3D issues state), and Ask AI to debug (general, not visual-specific).`,
  194: `Using AI to generate multiple design alternatives (layouts, color schemes, styles). Distinct from 2+ Design Frames (human considering multiple conceptual lenses), UI Fiddling (manual iterative adjustment), and Dubious Vibecoding (questionable AI code, not design).`,
  254: `Bayesian evidence-seeking strategy — "what observations would discriminate between hypotheses?" Distinct from Bayes Theorem (probability math once you have evidence), Find Cruxes (load-bearing beliefs in disagreements), and Specific Debugging Hypotheses (generating bug theories, not evidence strategy).`,
  327: `Making ambitious, multi-step, sophisticated requests to AI. Distinct from Ask LLM (noncode) (any non-code AI query regardless of complexity), Ask AI to debug (debugging specifically), and Tell AI "try simpler" (the retreat from failed complexity).`,
  281: `Delegating debugging to AI — "here's my problem, fix it." Hands-off approach. Distinct from Ask AI to help me do my own debug (human stays in control, AI supports), AI Identify Bug Cause (asking for diagnosis only, not fix), and Debugging (general state, not AI-specific).`,
  333: `Human-led debugging with AI as supporting resource — "help me understand this error" rather than "fix this for me." Distinct from Ask AI to debug (delegating the fix), AI Identify Bug Cause (targeted diagnostic query), and Specific Debugging Hypotheses (human-only, no AI).`,
  214: `Asking AI to refine/improve code it previously generated. Distinct from Ask AI to debug (fixing broken code), AI Code Review (requires "review" — evaluation, not improvement), Tell AI "try simpler" (specifically requesting simplification), and Rebuild/simplify Vibecode (human doing the simplification).`,
  236: `Using AI for any NON-code task — writing, research, brainstorming, explanations, planning. Catch-all for non-programming AI use. Distinct from all "Ask AI to..." coding tags and AI Extraction Summaries (a specific subset for document extraction).`,
  270: `Deliberately abandoning an unproductive AI conversation. Distinct from AI Failed (passive recognition AI failed) and Pivot from Vibecode (broader strategic shift away from AI coding approach, not just ending one chat).`,
  275: `Explicit application of Bayesian probability math — priors, posteriors, likelihood ratios, updating. Distinct from Fatebook (tracking predictions over time), Ask "how to get bits" (evidence-seeking strategy), and Find Cruxes (load-bearing beliefs in disagreements).`,
  280: `Using binary search/bisection to isolate a bug (especially git bisect). Distinct from git blame (viewing line-by-line authorship, not binary search), Specific Debugging Hypotheses (generating theories, not systematic elimination), and Debugging (general state, not this specific method).`,
  253: `BUILDING tools/features that incorporate AI — writing API calls to LLMs, designing prompts for programmatic use, creating AI-powered functionality. Distinct from all "Ask AI to..." tags (consuming AI assistance). Key question: "Am I building something that uses AI, or using AI to build something?"`,
  288: `Using Anthropic's standalone terminal-based Claude Code tool specifically (invoked via "cc" command). NOT Cursor's built-in AI panel even if using Claude model. Distinct from other AI coding tags by specifying WHICH TOOL, not what task.`,
  226: `HUMAN code review — reviewing colleague's PR, pair programming review. Distinct from AI Code Review (asking AI to review), PR Review (trigger for being in PR review state), and Read the Code (reading to understand, not to critique/evaluate).`,
  298: `Metacognitive reflection on your DEBUGGING PROCESS — "is my strategy working? What have I tried? Should I try a different approach?" Distinct from Specific Debugging Hypotheses (theories about the bug itself) and Debugging (the state of debugging, not reflecting on the process).`,
  207: `Human-driven synthesis of key insights/lessons from any experience. Distinct from AI Extraction Summaries (AI doing the extraction), Review Yesterday (specifically reviewing prior day), and Postmortem (structured incident analysis with root cause, not just insight extraction).`,
  305: `Deliberately consuming caffeine as energy/focus intervention. Distinct from Got Snack (food, not specifically caffeine), Tired (the fatigue state that might prompt caffeine), and Take a Break (rest-based intervention vs. stimulant-based).`,
  242: `Technique: deliberately proceeding with questionable AI code despite uncertainty. Distinct from Whirlwind Vibecode (emphasis on SPEED), Rebuild/simplify Vibecode (cleaning UP vibecode), Understand Complex Vibecode (slowing down to comprehend), and Pivot from Vibecode (abandoning the approach entirely).`,
  261: `Using the Fatebook prediction-tracking platform (fatebook.io) to record/manage/review probabilistic predictions. Look for fatebook.io in browser. Distinct from Bet Operationalization (making predictions precise enough to track — upstream work) and Bayes Theorem (probability math, not prediction tracking).`,
  235: `Identifying load-bearing beliefs in a disagreement — "what would change your mind?" Done DURING discussion. Distinct from Predict a Crux (forecasting cruxes BEFORE discussion), Ask "how to get bits" (broader evidence-seeking, not disagreement-specific), and Bayes Theorem (probability math).`,
  279: `Seeking external feedback on written prose (from humans or AI). Distinct from Code Review/AI Code Review (code, not prose), LW Writing (creating content, not seeking feedback on it), and Distill Takeaways (extracting insights, not receiving feedback).`,
  312: `Receiving massage therapy as self-care/pain intervention. Distinct from Take a Break (general rest), Workout (active exercise), Shoulder hurting (the pain state, not the response), and Appointment (the scheduling, not the technique).`,
  192: `Consciously abandoning a minor detail that's consuming disproportionate time. Distinct from Can't get small detail working (the stuck STATE — this is the RESOLUTION of that state) and Ship first ask questions later (broader shipping philosophy, not one specific detail).`,
  211: `Explicitly listing limitations/requirements/boundaries before generating solutions. Distinct from "What're my bottlenecks?" (throughput-limiting factor specifically), "What's my Goal?" (desired outcomes, not boundaries), and 2+ Plans (generating options within constraints — downstream of this).`,
  285: `Reading/parsing error messages and stack traces as primary diagnostic source. Distinct from Debugging (general state), Specific Debugging Hypotheses (generating theories about cause), Ask AI to debug (delegating to AI), and Bisect Tool (systematic commit elimination, not parsing error output).`,
  198: `Techniques: applying deliberate commenting methodology/rationalist discourse norms on LW. Distinct from LW Commenting (Projects = just the activity of commenting). Techniques version = consciously applying structured argumentation, crux-finding in comments, etc.`,
  309: `Brainstorming tasks appropriate for current low energy state — matching task difficulty to reduced capacity. Distinct from Tired (the fatigue STATE, not the response), Start Slightly More Productive Thing (incremental improvement from current activity, not energy-matching), and "What would excite me?" (seeking excitement, not accommodating low energy).`,
  293: `Creating Trigger-Action Plans — explicit if-then behavioral rules ("When X happens, I will do Y"). Distinct from "What's my Goal?" (clarifying objectives), 2+ Plans (generating strategic approaches), and Identify Constraints (finding limitations). Key feature: the if-then trigger-action structure.`,
  210: `Forcing function: either commit to MAKING something true through action, or admit you believe probability is ≤50%. Eliminates vague commitments. Distinct from Fatebook (tracking predictions), Bayes Theorem (probability math), and Find Cruxes (identifying load-bearing beliefs).`,
  188: `Using multiple AI agents/LLM instances SIMULTANEOUSLY. Distinct from Ask AI to debug and other single-AI tags (one AI at a time), Run parallel queries (broader — any parallel operations, not just AI), and Waiting for Agent (passively waiting for one AI).`,
  315: `Negotiation-style conversation with colleague Nate — competing interests, trade-offs, reaching agreement. Distinct from Talk to X tags (general consultation without negotiation dynamic) and argue with Robert (conflict state, not deliberate negotiation technique).`,
  337: `Metacognitive moment of catching yourself doing meta-work instead of object-level work. Distinct from Too Meta? (the concern/state), Orienting (legitimate orientation activity), and "What's my Goal?" (clarifying objectives, not noticing meta drift).`,
  201: `Metacognitive skill of NOTICING you're passively waiting for AI. The awareness moment that enables action. Distinct from Waiting for Agent (the state of waiting, without awareness) and Multiple agents/Run parallel queries (actions you might take AFTER noticing).`,
  212: `Deliberately deciding to stop UI polish/refinement work and redirect effort. Distinct from UI Fiddling (the activity OF fiddling — this is stopping it), Give up on small detail (any minor detail, not specifically UI), and Pivot from Vibecode (abandoning AI coding, not UI work).`,
  202: `Strategically abandoning AI-assisted coding approach entirely for a different methodology. Distinct from Bail on AI chat (ending one conversation, might start another), Rebuild/simplify Vibecode (staying in vibecode paradigm but cleaning up), and Understand Complex Vibecode (studying AI code to work with it).`,
  324: `Forecasting disagreement points BEFORE a discussion — "I predict the crux will be X." Distinct from Find Cruxes (discovering cruxes DURING discussion) and Fatebook (tracking predictions generally, not specifically crux prediction).`,
  190: `Building infrastructure to accelerate design iteration (Storybook, component playgrounds, preview systems). Distinct from UI Infra (broader foundational UI systems), UI Fiddling (doing the iteration, not building infrastructure for it), and Fast UI Test Tool (a specific named project that might be an instance of this technique).`,
  286: `Deliberately reading source code to build understanding — human-driven comprehension through direct study. Distinct from Understand Complex Vibecode (specifically AI-generated code), Investigate Error Message (parsing error output, not source code), git blame (examining history/authorship), and AI-assisted approaches.`,
  217: `Human takes ownership of rewriting/simplifying AI-generated code. Distinct from Ask AI to improve it's code (asking AI to fix its own code), Understand Complex Vibecode (comprehension-focused, not transformation), and Pivot from Vibecode (abandoning AI code entirely, not improving it).`,
  233: `Decomposing large code into smaller modules — extracting functions, splitting files, creating components. Direction: fewer/larger → more/smaller. Distinct from Remove Dead Code (deleting unused code), Rebuild/simplify Vibecode (simplifying AI code specifically), and Read the Code (understanding, not restructuring).`,
  220: `Identifying and deleting code that is never executed or referenced. Distinct from Refactor code into pieces (restructuring WORKING code), Rebuild/simplify Vibecode (simplifying AI code that IS being used), and Debugging (fixing broken code, not removing unused code).`,
  221: `Reviewing previous day's activities to orient for today — a daily reflection habit. Distinct from Orienting (broader, not specifically yesterday), Postmortem (structured incident analysis, not daily review), and Distill Takeaways (extracting insights from any source, not specifically yesterday).`,
  301: `Running multiple operations simultaneously to reduce total wait time (DB queries, tests, API calls, AI prompts). Distinct from Multiple agents (specifically multiple AI instances — a subset), Notice Waiting for Agent (awareness of waiting, not the parallelization action), and "What's fastest?" (asking about speed, not executing parallel operations).`,
  199: `Specific diplomatic phrase used with colleague Oli: flagging disagreement with phrasing while committing to charitable interpretation and forward progress. Distinct from Talk to Oli (general consultation) and Talking to Oli (state of being in conversation).`,
  185: `Prioritizing deployment velocity over completeness — "ship now, fix later." Distinct from Winging It (general improvisation, not specifically about deployment), "What's fastest?" (deliberation, not execution), and Dubious Vibecoding (questionable code quality, not shipping decisions).`,
  336: `Generating explicit, testable theories about bug causes BEFORE investigating — hypothesis-driven debugging by the HUMAN. Distinct from Debugging (general state), AI Identify Bug Cause (AI generating theories), Bisect Tool (systematic elimination without hypotheses), and Investigate Error Message (parsing error output).`,
  322: `Overcoming procrastination through incremental productivity improvement — move to something SLIGHTLY more productive than current activity. Gradient ascent. Distinct from List low-energy options (matching energy to tasks), "What would excite me?" (seeking excitement), and Dubiously Productive Procrastinating (the stuck state this technique addresses).`,
  191: `Metacognitive recognition of struggling to stay focused on the highest-value question — you KNOW what's important but can't maintain attention on it. Distinct from "What's my Goal?" (don't know the goal), Top Priority (successfully working on #1), and Bouncing (rapid switching behavior, not specifically away from the most important thing).`,
  193: `Deliberately choosing browser DevTools as debugging tool. Tool-focused, not problem-domain-focused. Distinct from Debugging CSS (problem domain, any tool), Investigate Error Message (examining error content, any tool), and AI debugging visuals (using AI, different tool).`,
  308: `Deliberately choosing to step away from work as a strategy. The DECISION to rest. Distinct from Break (Projects = logged time category), Break (Triggers = state of being on break), Take a Nap (sleep specifically), Take a Walk (walking specifically), and Drink Caffeine (stimulant instead of rest).`,
  306: `Deliberately napping as energy recovery — actual sleep. Distinct from Take a Break (general rest without sleep), Tired (the fatigue state, not the response), and Drink Caffeine (stimulant approach vs. sleep approach).`,
  307: `Walking as mental reset/thinking technique — lighter and shorter than Workout. Distinct from Workout (substantial exercise for fitness), Take a Break (general rest, not specifically walking), and Take a Nap (sleep-based, not movement-based).`,
  282: `Conversations specifically about AI futures, timelines, scenarios, development trajectories. Distinct from AI Research Meta (research methodology, not futures), AI 2030 Strategy (strategic planning for a specific project), and Ask LLM (noncode) (broader non-code AI use).`,
  266: `Deliberately consulting colleague Joanna for input/expertise. Distinct from Talk to Coworker (trigger for verbal conversations, manually logged), Talking to Oli (state of being in conversation with Oli), and other Talk to X tags (different specific people).`,
  265: `Deliberately consulting colleague John for input/expertise. Distinct from Talk to Coworker (verbal conversations requiring manual logging), Team Meeting (group meetings), and Negotiate with Nate (negotiation dynamic). Other Talk to X tags differ by person.`,
  272: `Deliberately consulting colleague Oli. Distinct from Talking to Oli (Trigger = state of being in conversation), Say "I don't buy that phrasing..." (specific diplomatic technique used with Oli), and Talk to Coworker (verbal conversations, manual logging).`,
  216: `Deliberately consulting colleague Robert. Distinct from argue with Robert (Trigger = contentious disagreement state, not neutral consultation), Talk to Coworker (verbal, manual logging), and other Talk to X tags (different people).`,
  332: `Directing AI to produce a SIMPLER solution than it initially generated. Distinct from Ask AI to improve it's code (general improvement, not specifically simplification), Rebuild/simplify Vibecode (human simplifying, not asking AI to), and Ask AI for complex thing (the opposite direction).`,
  289: `Self-directed prompt to accelerate cognitive processing speed — "can I think about this faster?" Distinct from "What's fastest?" (selecting fastest approach/path), Ship first ask questions later (shipping velocity), and Winging It (improvising without a plan, not speeding up deliberate thought).`,
  331: `Using ThoughtLogger's fact recording feature as a workflow tool. Distinct from ThoughtLogger (Projects = developing the app), Distill Takeaways (general human synthesis), and AI Extraction Summaries (AI doing the extraction). This is about using, not building, the tool.`,
  218: `Hands-on iterative adjustment of UI elements — tweaking CSS values, adjusting margins, polishing visual details. Trial-and-error refinement. Distinct from Debugging CSS (something is BROKEN), Design (broader design work state), Pivot from UI Finetuning (stopping this activity), and UI Infra (building foundational systems, not tweaking specific elements).`,
  213: `Building foundational UI systems — component libraries, design tokens, shared utilities, layout primitives. Distinct from UI Fiddling (adjusting specific elements, not building systems), Rapid Design Infra (specifically for rapid iteration), and Fast UI Test Tool (a specific named project).`,
  222: `Studying AI-generated code to build genuine understanding of how it works. Comprehension-focused. Distinct from Rebuild/simplify Vibecode (rewriting it), Dubious Vibecoding (proceeding without understanding), Read the Code (any codebase, not specifically AI-generated), and debugging tags (fixing problems, not studying working code).`,
  268: `Conducting structured conversations with actual USERS to gather qualitative feedback. Distinct from LW User Request (handling support tickets — reactive service), Talk to X tags (conversations with colleagues, not users), and Get Writing Feedback (feedback on writing specifically).`,
  323: `Comparing two+ code pieces to identify meaningful differences — "why does this work here but not there?" Distinct from Read the Code (understanding one piece in isolation), Specific Debugging Hypotheses (generating theories), git blame (examining authorship history), and Bisect Tool (binary search through commits).`,
  232: `Diagnosing what makes the current task difficult — categorizing the TYPE of difficulty (knowledge gap, tedium, ambiguity, emotional drain). Distinct from "What're my bottlenecks?" (throughput/flow framing), Identify Constraints (objective limitations), and Confused (passive state, not active diagnosis).`,
  200: `Rapid-fire AI-assisted coding at maximum speed — generate-accept-generate-accept with minimal review. Emphasis on PACE. Distinct from Dubious Vibecoding (emphasis on UNCERTAINTY/quality concern), Rebuild/simplify Vibecode (cleanup, not generation), and Understand Complex Vibecode (slowing down, opposite direction).`,
  256: `Consciously proceeding without a structured plan — improvising across any work type. Distinct from Ship first ask questions later (specifically about deployment decisions), Dubious Vibecoding (specifically AI coding, not general work), and 2+ Plans (the opposite — generating structured approaches).`,
  284: `Using git blame/annotate to investigate line-by-line code authorship and commit history. Distinct from Bisect Tool (binary search through commits to find bug introduction, not viewing line history), Read the Code (understanding functionality, not historical origins), and Code Review (evaluating proposed changes, not investigating existing history).`,

  // === Triggers ===
  283: `Recognition that an AI attempt failed to produce useful results. The awareness/state, not the response. Distinct from AI debug didn't work twice (requires TWO debugging failures specifically), Bail on AI chat (active decision to abandon — the response), Vibecode Bug (buggy code exists, not AI interaction failing), and Dubious Vibecoding (proceeding despite uncertainty, not definitive failure).`,
  330: `TWO failed AI debugging attempts on the same problem. Escalation trigger suggesting time to change strategy. Distinct from AI Failed (any single AI failure, any type) and Debugging (general debugging state without specifying AI failure count).`,
  104: `Complete arc of distraction AND return — got pulled away but successfully came back to original task quickly. Distinct from Bouncing Off (failing to engage, no return), Distracted by Notification (the initial interruption, not the recovery), and Dubiously Productive Procrastinating (engaging with wrong work, not returning).`,
  64: `Attempting to engage with a task but failing to get traction — the ball bounces OFF the surface. Failing to start ONE specific task. Distinct from Bouncing (rapid switching between MANY tasks), Confused (not understanding), Tired (physical state), and Dubiously Productive Procrastinating (successfully engaging with wrong work).`,
  75: `State/context of being on a break (Triggers category). Distinct from Break (Projects = time allocation tracking), Take a Break (Techniques = the decision to step away), and Tired (fatigue state that might prompt a break).`,
  143: `Bug discovered in code AI JUST generated — immediately failing on first use. The "fresh" = recency is key. Distinct from Vibecode Bug (any bug in AI code regardless of age) and AI Failed (AI interaction itself failing, not buggy output). Dubious Vibecoding is about the process feeling risky, not a specific bug found.`,
  41: `Stuck on a MINOR, non-essential detail despite repeated effort — frustrating mismatch between triviality and difficulty. Distinct from Debugging (general, any size bug), Confused (general uncertainty), Give up on small detail (the RESOLUTION of this state — choosing to stop), and Debugging CSS (CSS domain-specific, any importance level).`,
  128: `Passively browsing/monitoring Slack — reading messages, scanning channels. Distinct from DMing (actively composing/sending messages), Distracted by Notification (reactive interruption), and Missed a slack message (realized you overlooked something).`,
  34: `General mental uncertainty/confusion not specific to bugs, design, or postmortems. Use domain-specific confusion tags when applicable: Confused about bugs, Confused about Design, Confused about Postmortem. This is the catch-all.`,
  122: `Confusion/uncertainty specifically about design decisions — how should this look/work? Distinct from Confused (general), Debugging CSS (fixing broken styling, not deciding what styling should be), Design (broader state of doing design work, including confidently), and 2+ Design Frames (technique to address this confusion).`,
  295: `Confusion specifically during postmortem/retrospective analysis — unclear about methodology, timeline, root causes, or structure. Distinct from Confused (general), Confused about bugs (current debugging), and Postmortem (the Projects tag for the activity itself, without confusion).`,
  339: `Confusion specifically about bugs — "I have no idea what's causing this." Distinct from Debugging (general debugging state, could be non-confused), Confused (general, not bug-specific), Specific Debugging Hypotheses (actively generating theories — opposite of confused), and AI debug didn't work twice (pattern of failed AI attempts, not general confusion).`,
  257: `Actively composing/sending direct messages (primarily text-based). Distinct from Checking Slack (passive reading/browsing), Distracted by Notification (reactive interruption), Talk to Coworker (verbal/audio communication), and Talk to X tags (deliberate consultation strategy, not the messaging activity itself).`,
  344: `State of debugging 3D graphics/rendering issues (WebGL, three.js, camera, lighting, z-fighting). Distinct from Debugging CSS (2D styling), Debugging (general), AI debugging visuals (technique using AI, not the problem domain), and Globe project tags (which project, not what type of problem).`,
  55: `General state of debugging — investigating/fixing unexpected code behavior. The WHAT, not the HOW. Often co-occurs with technique tags describing approach (Ask AI to debug, Bisect Tool, Investigate Error Message, etc.). Distinct from domain-specific triggers: Debugging CSS, Debug 3D Visuals, Confused about bugs.`,
  42: `Debugging specifically CSS/styling issues — something is BROKEN, not being polished. Distinct from UI Fiddling (intentional refinement of working styles), Design (making design decisions), Debug 3D Visuals (3D rendering, not CSS), and Switch to Browser Inspector (the tool used, not the problem domain).`,
  33: `Currently in design-focused work state — making visual/UX decisions. Distinct from Debugging CSS (fixing broken styles), Confused about Design (stuck/uncertain), UI Fiddling (specific technique of small adjustments), and design technique tags (2+ Design Frames, Agent does design variations, etc.).`,
  103: `External notification involuntarily pulls attention from work — reactive, unplanned interruption. Distinct from Checking Slack (proactive, user chose to look), Bounced but bounced back (the recovery arc, not initial interruption), and DMing (actively messaging, not being interrupted).`,
  251: `Catching yourself doing something you explicitly committed NOT to do. Requires PRIOR commitment. Distinct from Dubiously Productive Procrastinating (avoidance without a specific prior commitment), Dubious Side Project (questionable prioritization), and Side Quest (tangential exploration without a rule against it).`,
  35: `Waiting for a downlift/code-sync operation to complete. Distinct from Waiting for Agent (waiting for AI), Merging (actively performing merge operations), and Multiple Codebases Bug (a bug caused by multi-repo interactions, not the waiting state).`,
  292: `Working on a side project while doubting whether it's a good use of time. Distinct from Side Quest (brief tangent/rabbit hole), Dubiously Productive Procrastinating (faux-productive avoidance of harder work), CAST Sideproject (a specific named project), and Doing Something I said I wouldn't (violating an explicit commitment).`,
  271: `Trigger: recognizing you're in dubious vibecoding mode — the STATE of accepting questionable AI code. Distinct from Dubious Vibecoding (Techniques = deliberately choosing to proceed), Vibecode Bug (a bug exists in AI code), AI Failed (AI definitively didn't succeed), and Whirlwind Vibecode (emphasis on speed, not quality doubt).`,
  276: `Doing tasks that FEEL productive but actually serve as avoidance of harder/more important work — answering low-priority emails, organizing files, reading tangentially. Distinct from Secondary Priority (legitimately working on second-tier tasks as conscious choice), Break (intentional rest), Side Quest (genuine exploration), and Dubious Side Project (sustained engagement with a separate project).`,
  79: `Acquired or eating a snack (not a full meal). Distinct from Lunch (midday meal), Drink Caffeine (specifically caffeinated beverages as energy strategy), Break (general rest without food specificity), and Tired (the fatigue state that might prompt snacking).`,
  345: `Questioning whether you're spending too much time on coordination/management vs. direct hands-on work. Distinct from Too Meta? (abstract meta-level thinking generally) and Orienting (figuring out what to do, not questioning management overhead).`,
  250: `Bug whose root cause stems from interactions between multiple codebases/repos. Distinct from Debugging (general), Vibecode Bug (AI-generated code bugs), Merging (the act of merging code), and Downlift Waiting (waiting for sync operations).`,
  158: `Discovering you overlooked/failed to notice a Slack message. Distinct from Checking Slack (actively browsing), Distracted by Notification (being interrupted by one), DMing (composing messages), and Ughy Message (emotional reaction to message content).`,
  328: `Unaccounted/unexplained gaps in time tracking. Distinct from Break (intentional rest), Procrastinating (avoidance), and Bouncing (rapid switching). This is about gaps you can't explain.`,
  148: `Engaged in operational/systems work — deployments, monitoring, server management, infrastructure operations. Distinct from Debugging (fixing code), Ray Infra (personal tooling), Globe Infra (globe-specific), and Merging (git merge specifically).`,
  23: `State of reviewing a Pull Request — viewing diffs, PR interfaces. Distinct from Code Review (Techniques = the practice of reviewing code methodically) and Merging (integrating code, not reviewing it). PR Review is the state/context, Code Review is the deliberate practice.`,
  338: `Previously working functionality now broken — a specific bug category. Distinct from Debugging (general), Bug in Fresh Vibecode (code never worked), Vibecode Bug (AI-generated bugs), and Can't get small detail working (minor stuck state, not regression).`,
  19: `Working on genuinely second-tier tasks as a CONSCIOUS choice given context. Distinct from Dubiously Productive Procrastinating (using second-tier tasks to AVOID first-tier), Top Priority (working on #1), and Doing Something I said I wouldn't (violating a commitment).`,
  343: `Physical shoulder pain/discomfort during work. Distinct from Tired (general fatigue), Get a massage (the response/technique), and Take a Break (general stepping away). This is the pain state itself.`,
  317: `Going off on a tangent/detour from main task — pursuing something tangential. Distinct from Dubious Side Project (sustained engagement with a separate project, not a brief tangent), Dubiously Productive Procrastinating (faux-productive avoidance, not genuine exploration), and Bouncing (rapid switching, not a focused tangent).`,
  255: `Verbal (AUDIO) conversation with any colleague. CANNOT be detected by AI — must be manually logged. Distinct from DMing (text-based messaging), Talk to X tags (deliberate consultation technique, includes text), and Talking to Oli (specific person trigger).`,
  68: `State of actively being in conversation with Oli right now. Distinct from Talk to Oli (Techniques = the deliberate DECISION to consult Oli) and Say "I don't buy that phrasing..." (a specific technique used within Oli conversations).`,
  82: `Physical/mental fatigue state. Distinct from Take a Nap (technique response to tiredness), Take a Break (technique of stepping away), Drink Caffeine (technique of stimulant), and List low-energy options (technique of matching tasks to energy). This is the state, not any response.`,
  117: `Questioning whether you've become too abstract/meta — working on frameworks rather than objects. Distinct from Managing Too Much? (specifically management overhead) and Notice I'm a few steps from working on the object-level (the active NOTICING technique, not the concern state).`,
  27: `Currently working on the highest-priority task. Distinct from Secondary Priority (second-tier), Struggling to focus on most important question (knows the priority but can't stay focused), and Orienting (figuring out what's important).`,
  296: `Physical difficulty typing — keyboard/hand/motor issues interfering with text input. Distinct from Shoulder hurting (different body part/type of pain), Tired (general fatigue), and Confused (mental, not physical).`,
  273: `Received a message that triggers negative emotional reaction — dread, frustration, anxiety. About the EMOTIONAL CONTENT of a message. Distinct from Checking Slack (passive browsing), DMing (composing messages), Distracted by Notification (the interruption, not the message content), and Missed a slack message (overlooking, not emotional reaction).`,
  291: `Resistance to updating beliefs or changing course despite evidence. Distinct from Doing Something I said I wouldn't (violating a commitment), Confused (not understanding), and Bouncing Off (failing to engage with a task).`,
  81: `Bug exists in AI-generated code of any age. Distinct from Bug in Fresh Vibecode (specifically just-generated code), Dubious Vibecoding (the risky process, not a specific bug), and AI Failed (the AI interaction failing, not buggy output).`,
  48: `Passively waiting for an AI agent to respond. Distinct from Notice Waiting for Agent (metacognitive awareness of waiting — the noticing moment), Multiple agents (parallelizing AI work), and Run parallel queries (executing operations in parallel).`,
  52: `State of being in an argument/disagreement with colleague Robert. Distinct from Talk to Robert (Techniques = neutral consultation), Team Meeting (group coordination), and Negotiate with Nate (structured negotiation, different person and dynamic).`,
  302: `Performing git merge operations or code integration. Distinct from PR Review (reviewing changes before merge), Downlift Waiting (waiting for sync), and Multiple Codebases Bug (bugs from multi-repo interactions).`,
}

const main = async () => {
  const allTags = await prisma.tag.findMany({ orderBy: [{ type: 'asc' }, { name: 'asc' }] })
  console.log(`Found ${allTags.length} tags total, ${Object.keys(descriptions).length} descriptions to update`)
  let updated = 0
  let totalCharsSaved = 0
  const missingIds = Object.keys(descriptions).map(Number).filter(id => !allTags.find(t => t.id === id))
  if (missingIds.length > 0) {
    console.log(`WARNING: ${missingIds.length} IDs in descriptions map not found in DB: ${missingIds.join(', ')}`)
  }
  const tagsNotUpdated = allTags.filter(t => !descriptions[t.id] && t.description && t.description.length > 300)
  if (tagsNotUpdated.length > 0) {
    console.log(`WARNING: ${tagsNotUpdated.length} tags with long descriptions NOT in update map:`)
    for (const t of tagsNotUpdated) {
      console.log(`  - ${t.type}/${t.name} (id=${t.id}, ${t.description?.length} chars)`)
    }
  }
  for (const [idStr, newDesc] of Object.entries(descriptions)) {
    const id = Number(idStr)
    const tag = allTags.find(t => t.id === id)
    if (!tag) continue
    const oldLen = tag.description?.length || 0
    const newLen = newDesc.length
    const saved = oldLen - newLen
    totalCharsSaved += saved
    await prisma.tag.update({ where: { id }, data: { description: newDesc } })
    console.log(`✓ ${tag.type}/${tag.name}: ${oldLen} → ${newLen} chars (saved ${saved})`)
    updated++
  }
  console.log(`\nDone. Updated ${updated} tags. Total chars saved: ${totalCharsSaved}`)
  process.exit(0)
}

main()
